name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Enforce branch protection rules
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/branches/main/protection
          mediaType: |
            previews:
              - luke-cage
          branch: main
          required_status_checks:
            strict: true
            contexts: []
          enforce_admins: true
          required_pull_request_reviews:
            dismissal_restrictions: {}
            dismiss_stale_reviews: true
            require_code_owner_reviews: true
            required_approving_review_count: 2
          restrictions: null
